-- MySQL Script generated by MySQL Workbench
-- 05/13/19 22:44:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ingsoft
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ingsoft` ;

-- -----------------------------------------------------
-- Schema ingsoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ingsoft` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `ingsoft` ;

-- -----------------------------------------------------
-- Table `ingsoft`.`residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`residencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `capacidad` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `en_subasta` ENUM('si', 'no') NOT NULL,
  `en_hotsale` ENUM('si', 'no') NOT NULL,
  `descrip` TEXT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idresidencia_UNIQUE` ON `ingsoft`.`residencia` (`id` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `suscripto` ENUM('si', 'no') NOT NULL,
  `tarjeta_credito` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idusuario_UNIQUE` ON `ingsoft`.`usuario` (`id` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_residencia` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `periodo` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_residencia1_idx` (`id_residencia` ASC),
  INDEX `fk_reserva_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_reserva_id_residencia`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `ingsoft`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ingsoft`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idreserva_UNIQUE` ON `ingsoft`.`reserva` (`id` ASC);

CREATE INDEX `id_residencia_idx` ON `ingsoft`.`reserva` (`id_residencia` ASC);

CREATE INDEX `id_usuario_idx` ON `ingsoft`.`reserva` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`periodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_residencia` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_periodo_residencia1_idx` (`id_residencia` ASC),
  CONSTRAINT `fk_periodo_residencia1`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `ingsoft`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ingsoft`.`periodo` (`id` ASC);

CREATE INDEX `id_residencia_idx` ON `ingsoft`.`periodo` (`id_residencia` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`hotsale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`hotsale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_residencia` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `periodo` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hotsale_residencia1_idx` (`id_residencia` ASC),
  CONSTRAINT `fk_hotsale_residencia1`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `ingsoft`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ingsoft`.`hotsale` (`id` ASC);

CREATE INDEX `id_residencia_idx` ON `ingsoft`.`hotsale` (`id_residencia` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`subasta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`subasta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_residencia` INT NOT NULL,
  `monto_inicial` DOUBLE NOT NULL,
  `periodo` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subasta_residencia1_idx` (`id_residencia` ASC),
  CONSTRAINT `fk_subasta_residencia1`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `ingsoft`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ingsoft`.`subasta` (`id` ASC);

CREATE INDEX `id_residencia_idx` ON `ingsoft`.`subasta` (`id_residencia` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`puja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`puja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_subasta` INT NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_puja_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_puja_subasta_idx` (`id_subasta` ASC),
  CONSTRAINT `fk_puja_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ingsoft`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puja_id_subasta`
    FOREIGN KEY (`id_subasta`)
    REFERENCES `ingsoft`.`subasta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ingsoft`.`puja` (`id` ASC);

CREATE INDEX `id_usuario_idx` ON `ingsoft`.`puja` (`id_usuario` ASC);

CREATE INDEX `id_subasta_idx` ON `ingsoft`.`puja` (`id_subasta` ASC);


-- -----------------------------------------------------
-- Table `ingsoft`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingsoft`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `ingsoft`.`administrador` (`id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
